// <auto-generated />
using System;
using Cretu_Alexandru_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cretu_Alexandru_Project.Migrations
{
    [DbContext(typeof(Cretu_Alexandru_ProjectContext))]
    partial class Cretu_Alexandru_ProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Cretu_Alexandru_Project.Models.Echipament", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Instrumente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipEchipament")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Echipament");
                });

            modelBuilder.Entity("Cretu_Alexandru_Project.Models.Reprezentant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("ID");

                    b.ToTable("Reprezentant");
                });

            modelBuilder.Entity("Cretu_Alexandru_Project.Models.Rezervare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<DateTime>("DataInceput")
                        .HasColumnType("datetime2");

                    b.Property<int>("EchipamentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OraInceput")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalaID")
                        .HasColumnType("int");

                    b.Property<int>("Timp")
                        .HasColumnType("int");

                    b.Property<int>("TrupaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("EchipamentId");

                    b.HasIndex("SalaID");

                    b.HasIndex("TrupaID");

                    b.ToTable("Rezervare");
                });

            modelBuilder.Entity("Cretu_Alexandru_Project.Models.Sala", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Locatie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumeSala")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("Suprafata")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("ID");

                    b.ToTable("Sala");
                });

            modelBuilder.Entity("Cretu_Alexandru_Project.Models.Trupa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("NumeTrupa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ReprezentantID")
                        .HasColumnType("int");

                    b.Property<int>("numarPersoane")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ReprezentantID");

                    b.ToTable("Trupa");
                });

            modelBuilder.Entity("Cretu_Alexandru_Project.Models.Rezervare", b =>
                {
                    b.HasOne("Cretu_Alexandru_Project.Models.Echipament", "Echipament")
                        .WithMany()
                        .HasForeignKey("EchipamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cretu_Alexandru_Project.Models.Sala", "Sala")
                        .WithMany()
                        .HasForeignKey("SalaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Cretu_Alexandru_Project.Models.Trupa", "Trupa")
                        .WithMany()
                        .HasForeignKey("TrupaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Echipament");

                    b.Navigation("Sala");

                    b.Navigation("Trupa");
                });

            modelBuilder.Entity("Cretu_Alexandru_Project.Models.Trupa", b =>
                {
                    b.HasOne("Cretu_Alexandru_Project.Models.Reprezentant", "Reprezentant")
                        .WithMany()
                        .HasForeignKey("ReprezentantID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reprezentant");
                });
#pragma warning restore 612, 618
        }
    }
}
